### ISSUE TITLE
pagination not working

### ISSUE THREAD

**Issue by marfalkov** [storyblok/bootstrap-demo#1]
It might be `articles.total` at [/views/components/_pagination.liquid#L8](https://github.com/storyblok/bootstrap-demo/blob/f5c233eb56955175a4ed4f66beccef0f217debf4/views/components/_pagination.liquid#L8)

missing `per_page` parameter at  [/views/components/_article_overview.liquid#L13](https://github.com/storyblok/bootstrap-demo/blob/f5c233eb56955175a4ed4f66beccef0f217debf4/views/components/_article_overview.liquid#L13) and [/views/components/_article_overview.liquid#L15](https://github.com/storyblok/bootstrap-demo/blob/f5c233eb56955175a4ed4f66beccef0f217debf4/views/components/_article_overview.liquid#L15)

Also the uikit classes doesn't get styles inside a bootstrap project.

**Comment by onefriendaday** [comment]
Thank you!

The code has been adapted.

**Comment by marfalkov** [comment]
Nice to see quick actions like this, and also the [storyblok CLI](https://github.com/storyblok/storyblok/commit/602dc087ca9c148ee5ea0a4617836127ba0d000d).
Thank You!
